project:
  type: book
  output-dir: docs
  
execute: 
  warning: FALSE
  message: FALSE
  cache: true
  freeze: auto

comments:
  hypothesis: 
    theme: clean

book:
  title: "Headwater streamflow variability is amplified by drought"
  author: "Jeff Baldock et al."
  date: today
  chapters:
    - index.qmd
    - GatherFlowClimateData.qmd
    - SpaceTimeVar.qmd
    - VarByClimate.qmd
    - ReferenceLowFlow.qmd
    - ModeledQ_StreamStats.qmd


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-overflow: wrap
    number-depth: 4
    
    include-in-header:
      - file: github-corner.html
    code-link: true
      
  pdf:
    documentclass: scrreprt

editor: source